swagger: '2.0'
info:
  description: 为API生，为框架死，为debug奋斗一辈子；吃符号亏，上大小写的当，最后死在需求上   ------- 梦旋飞
  version: 1.0.0
  title: 开发平台

basePath: /taobao_interface

schemes:
  - http

#认证
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "token"
    in: "header"

#定义接口数据
paths:


  /taobao/getGoods:
    get:
      tags:
        - 公共接口
      summary: 根据商品url获取商品信息。返回参考https://union.jd.com/openplatform/api/10422
      produces:
        - application/json
      parameters:
        - name: url
          description: 商品链接。测试链接https://detail.tmall.com/item.htm?id=569505623525&skuId=4318510539626
          in: query
          type: string
          required: true
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'



  /taobao/testAct:
    get:
      tags:
        - 公共接口
      summary: 测试获取活动信息
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'


  /taobao/testActDetail:
    get:
      tags:
        - 公共接口
      summary: 测试获取活动商品详细信息
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'




  /taobao/testOrder:
    get:
      tags:
        - 公共接口
      summary: 测试获取服务费订单信息
      produces:
        - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/R'








#定义数据模型
definitions:
  R:
      type: object
      properties:
        code:
          description: 状态码 0：成功  非0：失败
          type: integer
          format: int32
        msg:
          description: 失败原因
          type: string
